import quantumMath.*;import spMath.*;import java.lang.reflect.*;import java.util.*;
public class QuantumKeplerReference {
 static Object f(Object x,String n)throws Exception{Field z=x.getClass().getDeclaredField(n);z.setAccessible(true);return z.get(x);}
 public static void main(String[]args)throws Exception {
  double[][] cases={{100,2},{50,.5},{150,5}};System.out.println("[");
  for(int ci=0;ci<cases.length;ci++){double[]p=cases[ci];Hydrogen3DKepler b=new Hydrogen3DKepler(1600,40000,.35*Math.PI,.5*Math.PI,0,2*Math.PI,50,10,300);b.buildAndSetAmplitudeForKepler((int)p[0],p[1]);ArrayList<?> q=b.getQList();
  System.out.printf(java.util.Locale.ROOT,"{\"parameters\":[%g,%g],\"selected\":%d,\"initialMax\":%.17g,\"coefficient0\":[",p[0],p[1],q.size(),(Double)f(b,"maxAmplitude"));Object first=q.get(0);Complex a=(Complex)f(first,"amplitude");System.out.printf(java.util.Locale.ROOT,"%d,%d,%d,%.17g,%.17g],\"samples\":[",(Integer)f(first,"n"),(Integer)f(first,"l"),(Integer)f(first,"m"),a.re(),a.im());
  double[][] points={{p[0]*p[0],1.56,3.1,0},{p[0]*p[0]*.95,1.4,2.8,1e-12},{p[0]*p[0]*1.1,1.5,.6,3e-11},{p[0]*p[0],1.56,3.1,-5e-12}};for(int i=0;i<points.length;i++){double[]pt=points[i];Complex s=new Complex(0,0);for(Object o:q){int n=(Integer)f(o,"n"),l=(Integer)f(o,"l"),m=(Integer)f(o,"m");double e=(Double)f(o,"E");Complex c=(Complex)f(o,"amplitude");s=s.add(c.mul(Complex.polar(1,-e*pt[3]/6.58211928e-16)).mul(Complex.polar(HydrogenWaveFtn.Radial_n_n_1(n+(int)Math.ceil(p[0]+4*p[1])-(int)Math.floor(p[0]-4*p[1]),pt[0])*HydrogenWaveFtn.Theta_l_l(l,pt[1]),m*pt[2])));}System.out.printf(java.util.Locale.ROOT,"%s{\"point\":[%g,%g,%g,%g],\"re\":%.17g,\"im\":%.17g}",i>0?",":"",pt[0],pt[1],pt[2],pt[3],s.re(),s.im());}System.out.print("],\"gridSamples\":[");double[][] R=(double[][])f(b,"radialFtn"),T=(double[][])f(b,"thetaFtn");Complex[][] P=(Complex[][])f(b,"phiFtn");int start=(Integer)f(b,"nStart");double[][] gpoints={{10,10,150,0},{25,8,180,1e-12},{42,9,125,-5e-12}};for(int j=0;j<gpoints.length;j++){double[]pt=gpoints[j];Complex sum=new Complex(0,0);for(Object o:q){int n=(Integer)f(o,"n"),l=(Integer)f(o,"l"),mm=(Integer)f(o,"m");Complex c=(Complex)f(o,"amplitude");double e=(Double)f(o,"E");sum=sum.add(c.mul(Complex.polar(1,-e*pt[3]/6.58211928e-16)).mul(P[mm-start+1][(int)pt[2]].scale(R[n-start][(int)pt[0]]*T[l-start+1][(int)pt[1]])));}System.out.printf(java.util.Locale.ROOT,"%s{\"point\":[%g,%g,%g,%g],\"re\":%.17g,\"im\":%.17g}",j>0?",":"",pt[0],pt[1],pt[2],pt[3],sum.re(),sum.im());}System.out.print("]}"+(ci<cases.length-1?",":""));}
  System.out.println("]");
 }
}
