import java.lang.reflect.*;import java.util.*;import sun.misc.Unsafe;
public class QuantumModernReference {
 static Unsafe unsafe;static{try{Field f=Unsafe.class.getDeclaredField("theUnsafe");f.setAccessible(true);unsafe=(Unsafe)f.get(null);}catch(Exception e){throw new RuntimeException(e);}}
 static void set(Object o,String n,Object v)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);f.set(o,v);}
 static Object call(Object o,String n,Class<?>[]ts,Object...a)throws Exception{Method m=o.getClass().getDeclaredMethod(n,ts);m.setAccessible(true);return m.invoke(o,a);}
 static String probes(Object a)throws Exception{int N=Array.getLength(a);String s="[";for(int j:new int[]{0,1,N/4,N/2,N-2,N-1}){Object z=Array.get(a,j);s+=(s.length()>1?",":"")+"["+j+","+z.getClass().getMethod("re").invoke(z)+","+z.getClass().getMethod("im").invoke(z)+"]";}return s+"]";}
 static reldistortion.Point3D pt()throws Exception{Constructor<?> c=reldistortion.Point3D.class.getDeclaredConstructor(double.class,double.class,double.class);c.setAccessible(true);return (reldistortion.Point3D)c.newInstance(100.,50.,400.);}
 public static void main(String[]args)throws Exception{Locale.setDefault(Locale.ROOT);ArrayList<String>rows=new ArrayList<>();
 for(String c:new String[]{"balckbody.Blackbody0","balckbody.Blackbody1"})for(int T:new int[]{0,50,5000,10000}){Object o=unsafe.allocateInstance(Class.forName(c));set(o,"temperature",(double)T);for(double w:new double[]{0,4,5,100,550,2000,5000})for(String method:new String[]{"blackbodySpectrum","blackbodySpectrum_Rayleigh"})rows.add("{\"kind\":\"blackbody\",\"class\":\""+c+"\",\"T\":"+T+",\"w\":"+w+",\"rayleigh\":"+method.endsWith("Rayleigh")+",\"value\":"+call(o,method,new Class[]{double.class},w)+"}");}
 for(int n:new int[]{1,10,25})for(double t:new double[]{0,.1,3}){Object o=unsafe.allocateInstance(Class.forName("OneDim"));set(o,"amplitude",45.);set(o,"wavenumber",Math.PI*n/500);set(o,"frequency",Math.PI*n/10);rows.add("{\"kind\":\"resonant1\",\"n\":"+n+",\"x\":133,\"t\":"+t+",\"value\":"+call(o,"waveFtn",new Class[]{double.class,double.class},133.,t)+"}");}
 for(int nx:new int[]{1,10,25})for(int ny:new int[]{1,10,25})for(double t:new double[]{0,.1,3}){Object o=unsafe.allocateInstance(Class.forName("TwoDim"));set(o,"amplitude",45.);set(o,"kX",Math.PI*nx/400);set(o,"kY",Math.PI*ny/400);set(o,"frequency",Math.PI*Math.hypot(nx,ny)/4);rows.add("{\"kind\":\"resonant2\",\"nx\":"+nx+",\"ny\":"+ny+",\"t\":"+t+",\"value\":"+call(o,"waveFtn",new Class[]{double.class,double.class,double.class},133.,177.,t)+"}");}
 for(int n=1;n<=7;n++)for(boolean clockwise:new boolean[]{false,true})for(double t:new double[]{0,.1,10}){double r=4*n*n,theta=.73;Class<?>c=Class.forName("Electron");Constructor<?>co=c.getDeclaredConstructor(double.class,double.class,boolean.class,double.class);co.setAccessible(true);Object e=co.newInstance(200+r*Math.cos(theta),200+r*Math.sin(theta),clockwise,0.);c.getMethod("calcPosition",double.class).invoke(e,t);Field x=c.getDeclaredField("x"),y=c.getDeclaredField("y");x.setAccessible(true);y.setAccessible(true);rows.add("{\"kind\":\"bohr\",\"n\":"+n+",\"clockwise\":"+clockwise+",\"t\":"+t+",\"x\":"+x.getDouble(e)+",\"y\":"+y.getDouble(e)+"}");}
 for(double v:new double[]{-.9,0,.25,.9})for(double t:new double[]{0,25,200}){reldistortion.Relativity r=new reldistortion.Relativity(v);reldistortion.Point3D z=r.relTrans(pt(),t);rows.add("{\"kind\":\"relativity\",\"v\":"+v+",\"t\":"+t+",\"value\":"+z.getX()+"}");}
 onedimquantum.Complex[]u=new onedimquantum.Complex[64];for(int j=0;j<64;j++)u[j]=new onedimquantum.Complex(Math.sin(j*.31),Math.cos(j*.07));rows.add("{\"kind\":\"fft\",\"inverse\":true,\"samples\":"+probes(onedimquantum.FFT1D.FFTransform1D(u,true,true))+"}");rows.add("{\"kind\":\"fft\",\"inverse\":false,\"samples\":"+probes(onedimquantum.FFT1D.FFTransform1D(u,false,true))+"}");
 for(int type=0;type<8;type++){double[]v=new double[1024];int C=512,H=5000,W=100;for(int j=0;j<1024;j++){switch(type){case 0:v[j]=j>=462&&j<562?H:0;break;case 1:v[j]=j>=462&&j<=562?0:H;break;case 2:v[j]=j>=C?H:0;break;case 4:v[j]=H/512./512*(j-C)*(j-C);break;case 5:v[j]=H/512.*Math.abs(j-C);break;case 6:v[j]=((Math.abs(j-512)+50)/100)%2==1?H:0;break;case 7:double x=Math.abs((j-C)*.005);v[j]=x>.25?H*.25/2/x:-2000;}}
 Class<?>cl=Class.forName("onedimquantum.Quantum1D");Constructor<?>co=cl.getDeclaredConstructors()[0];co.setAccessible(true);Object q=co.newInstance(1024,.005,1.,v);onedimquantum.Complex[]a=new onedimquantum.Complex[1024];for(int j=0;j<1024;j++){double x=.005*(j-152);a[j]=onedimquantum.Complex.polar(Math.exp(-x*x/.04),25*x);}for(int step:new int[]{0,1,9}){if(step>0)for(int k=0;k<(step==1?1:8);k++)cl.getMethod("calcNext",a.getClass()).invoke(q,(Object)a);rows.add("{\"kind\":\"potential1\",\"type\":"+type+",\"step\":"+step+",\"samples\":"+probes(a)+"}");}}
 for(int n:new int[]{3,16})for(int po:new int[]{0,10000}){twodimquantum.Complex[][]a=new twodimquantum.Complex[n][n];double[][]v=new double[n][n];for(int x=0;x<n;x++)for(int y=0;y<n;y++){a[x][y]=twodimquantum.Complex.polar(Math.exp(-(x*x+y*y)/20.),x*.3+y*.5);v[x][y]=po*(x-y)*(x-y)/(double)(n*n);}twodimquantum.Quantum2D q=new twodimquantum.Quantum2D();q.setPotential(v,4,1./32768);for(int k=0;k<2;k++)q.calcNext(a);ArrayList<String>samples=new ArrayList<>();for(int x:new int[]{0,n/2,n-1})for(int y:new int[]{0,n/2,n-1})samples.add("["+x+","+y+","+a[x][y].re()+","+a[x][y].im()+"]");rows.add("{\"kind\":\"potential2kernel\",\"N\":"+n+",\"po\":"+po+",\"samples\":["+String.join(",",samples)+"]}");}
 for(int n=1;n<=7;n++)for(int l=0;l<n;l++)for(int m=-l;m<=l;m++){spMath.Complex z=quantumMath.HydrogenWaveFtn.Psi(n,l,m,2.3,.7,.9);rows.add("{\"kind\":\"hydrogen\",\"n\":"+n+",\"l\":"+l+",\"m\":"+m+",\"re\":"+z.re()+",\"im\":"+z.im()+"}");}
 for(int n=1;n<=7;n++)for(int l=0;l<n;l++)for(int m=0;m<=l;m++){double r=Math.hypot(2.3,1.1),theta=Math.atan2(2.3,1.1),value=hydrogen.HydrogenMath.Radial(n,l,r)*hydrogen.HydrogenMath.SphericalHarmonicsNorm(l,m,theta);rows.add("{\"kind\":\"cloud\",\"n\":"+n+",\"l\":"+l+",\"m\":"+m+",\"value\":"+value+"}");}
 System.out.println("["+String.join(",\n",rows)+"]");}
}
