import java.lang.reflect.*;import java.util.*;import sun.misc.Unsafe;
public class QuantumPacketReference {
 static Unsafe u;static{try{Field f=Unsafe.class.getDeclaredField("theUnsafe");f.setAccessible(true);u=(Unsafe)f.get(null);}catch(Exception e){throw new RuntimeException(e);}}
 static void set(Object o,String n,Object v)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);f.set(o,v);}static Object get(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 static void call(Object o,String n,Class<?>[]ts,Object...a)throws Exception{Method m=o.getClass().getDeclaredMethod(n,ts);m.setAccessible(true);try{m.invoke(o,a);}catch(InvocationTargetException e){if(!(e.getCause() instanceof NullPointerException))throw e;}}
 static String probes(Object a)throws Exception{int N=Array.getLength(a);String s="[";for(int j:new int[]{0,1,N/4,N/2,N-2,N-1}){Object z=Array.get(a,j);s+=(s.length()>1?",":"")+"["+j+","+z.getClass().getMethod("re").invoke(z)+","+z.getClass().getMethod("im").invoke(z)+"]";}return s+"]";}
 static String probes2(Object a)throws Exception{int N=Array.getLength(a),M=Array.getLength(Array.get(a,0));String s="[";for(int x:new int[]{0,N/4,N/2,N-1})for(int y:new int[]{0,M/4,M/2,M-1}){Object z=Array.get(Array.get(a,x),y);s+=(s.length()>1?",":"")+"["+x+","+y+","+z.getClass().getMethod("re").invoke(z)+","+z.getClass().getMethod("im").invoke(z)+"]";}return s+"]";}
 public static void main(String[]args)throws Exception{ArrayList<String>rows=new ArrayList<>();for(String kind:new String[]{"freeParticle","freeBox","freeRing"})for(int shape=0;shape<6;shape++)for(int variant=0;variant<3;variant++)for(boolean classical:new boolean[]{false,true}){if(kind.equals("freeParticle")&&classical)continue;int N=kind.equals("freeParticle")?8192:kind.equals("freeBox")?1024:512,W=kind.equals("freeParticle")?800:512;double k=variant==0?(kind.equals("freeRing")?61:kind.equals("freeBox")?30:25):variant==1?-10:100,width=variant==0?20:variant==1?1:40;boolean fixed=variant!=1;Object o=u.allocateInstance(Class.forName("onedimquantum."+kind));Class<?>z=Class.forName("onedimquantum.Complex");set(o,"psi",Array.newInstance(z,N));set(o,"psiT",Array.newInstance(z,N));if(!kind.equals("freeRing")){set(o,"windowPt",W);set(o,"psiWindow",Array.newInstance(z,W));}if(kind.equals("freeParticle")){Field tt=o.getClass().getDeclaredField("jslTime");tt.setAccessible(true);Constructor<?> co=tt.getType().getDeclaredConstructor();co.setAccessible(true);tt.set(o,co.newInstance());}set(o,"shapeNumber",shape);set(o,"k0",shape==5&&!kind.equals("freeParticle")?k*2*Math.PI/(N*.005):k);set(o,"width",width);if(!kind.equals("freeParticle"))set(o,"isClassical",classical);if(kind.equals("freeBox"))set(o,"isFixed",fixed);call(o,"generateFtn",new Class[]{});for(int t:new int[]{0,1,33}){if(t>0)call(o,"draw",new Class[]{double.class},(double)t);Object field=get(o,kind.equals("freeRing")?"psi":"psiWindow");rows.add("{\"kind\":\""+kind+"\",\"shape\":"+shape+",\"k\":"+k+",\"width\":"+width+",\"fixed\":"+fixed+",\"classical\":"+classical+",\"time\":"+t+",\"samples\":"+probes(field)+"}");}}
 for(int shape=0;shape<6;shape++)for(boolean fixed:new boolean[]{false,true}){Class<?>z=twodimquantum.Complex.class;Object o=u.allocateInstance(Class.forName("twodimquantum.twoDimBox"));set(o,"psi",Array.newInstance(z,512,256));set(o,"psiT",Array.newInstance(z,512,256));set(o,"psiWindow",Array.newInstance(z,256,128));set(o,"shapeNumber",shape);set(o,"isFixed",fixed);set(o,"isClassical",false);set(o,"waveX",.5);set(o,"waveY",.25);set(o,"widthX",5./512);set(o,"widthY",5./512);set(o,"waveKx",shape==5?40*2*Math.PI:40.);set(o,"waveKy",shape==5?20*4*Math.PI:20.);call(o,"initial_wave",new Class[]{});for(int t:new int[]{0,1,33}){if(t>0)call(o,"draw",new Class[]{double.class},(double)t);rows.add("{\"kind\":\"free2D\",\"shape\":"+shape+",\"fixed\":"+fixed+",\"time\":"+t+",\"samples\":"+probes2(get(o,"psiWindow"))+"}");}}
 System.out.println("["+String.join(",\n",rows)+"]");}
}
