import java.lang.reflect.*;import java.util.*;import sun.misc.Unsafe;import javax.swing.JCheckBox;
public class QuantumPotentialReference {
 static Unsafe u;static{try{Field f=Unsafe.class.getDeclaredField("theUnsafe");f.setAccessible(true);u=(Unsafe)f.get(null);}catch(Exception e){throw new RuntimeException(e);}}
 static void set(Object o,String n,Object v)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);f.set(o,v);}static Object get(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}
 static void call(Object o,String n)throws Exception{Method m=o.getClass().getDeclaredMethod(n);m.setAccessible(true);try{m.invoke(o);}catch(InvocationTargetException e){if(!(e.getCause() instanceof NullPointerException))throw e;}}
 static String samples(twodimquantum.Complex[][] a){String s="[";for(int x:new int[]{0,25,55,96,127})for(int y:new int[]{0,32,65,96,127}){s+=(s.length()>1?",":"")+"["+x+","+y+","+a[x][y].re()+","+a[x][y].im()+"]";}return s+"]";}
 public static void main(String[]args)throws Exception{ArrayList<String>rows=new ArrayList<>();for(String kind:new String[]{"twoDimHarmonicOsc","twoDimQuantum","twoParticleDI","twoParticleFD"})for(int variant=0;variant<3;variant++)for(int type=0;type<(kind.equals("twoDimQuantum")?10:1);type++)for(boolean symmetric:new boolean[]{false,true}){if(!kind.equals("twoParticleFD")&&!symmetric)continue;Object o=u.allocateInstance(Class.forName("twodimquantum."+kind));set(o,"psi",new twodimquantum.Complex[128][128]);set(o,"potential",new double[128][128]);set(o,"poX",.5);set(o,"poY",.5);set(o,"q2",new twodimquantum.Quantum2D());set(o,"epsilon",1./128);set(o,"del",1./32768);double x0=variant==0?.25:variant==1?.2:.8,y0=kind.equals("twoParticleFD")?.75:kind.equals("twoDimQuantum")?.25:.2,kx=variant==0?(kind.equals("twoParticleFD")?0:25):variant==1?-100:100,ky=kind.equals("twoDimQuantum")?25:0,uncertainty=variant==0?.05:variant==1?.03:.1;set(o,"waveX",x0);set(o,"waveY",y0);set(o,"waveKx",kx);set(o,"waveKy",ky);
 if(kind.equals("twoParticleDI")||kind.equals("twoParticleFD")){set(o,"waveUncertaintyX",uncertainty);set(o,"waveUncertaintyY",.05);}else set(o,"waveUncertainty",uncertainty);
 if(kind.equals("twoDimQuantum")){set(o,"poType",type);set(o,"poMax",1000.);set(o,"poScale",1.);}else {set(o,"springConstantX",variant==1?0.:variant==2?100000.:50000.);set(o,"springConstantY",50000.);}if(kind.equals("twoParticleFD")){JCheckBox b=new JCheckBox();b.setSelected(symmetric);set(o,"jcbSymmetry",b);}call(o,"setPotential");((twodimquantum.Quantum2D)get(o,"q2")).setPotential((double[][])get(o,"potential"),4.,1./32768);call(o,"initial_wave");twodimquantum.Complex[][]a=(twodimquantum.Complex[][])get(o,"psi");twodimquantum.Quantum2D q=(twodimquantum.Quantum2D)get(o,"q2");for(int t:new int[]{0,2,20}){if(t>0)for(int j=0;j<(t==2?2:18);j++)q.calcNext(a);rows.add("{\"kind\":\""+kind+"\",\"variant\":"+variant+",\"type\":"+type+",\"symmetric\":"+symmetric+",\"step\":"+t+",\"samples\":"+samples(a)+"}");}}
 System.out.println("["+String.join(",\n",rows)+"]");}
}
