import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {apertureSpecs,apertureDefaults,apertureState,airy,rectAmplitude,rectFresnel,zernikeR,pupilValue,apertureCSV,projectPupil} from '../assets/aperture-physics.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-7*Math.max(1,Math.abs(a),Math.abs(b)),a+' / '+b);
test('Airy central limit and known first Bessel zero preserve intensity and wavelength scaling',()=>{near(airy(0),1);assert.ok(airy(3.8317059702075125)<1e-20);for(const x of [.1,1,2,8,15])near(airy(x),airy(-x));const p={wl:500,amp:10},q=apertureState('circle',p);near(q.rings[0].intensity,10);near(q.rings[25].intensity,airy(7.5,10));});
test('Rectangular Fresnel intensities are even, zero for zero aperture and separable in two dimensions',()=>{for(const w of [.4,1,4,10])for(const x of [0,.05,1,5,9.95])near(rectAmplitude(x,w),rectAmplitude(-x,w));near(rectAmplitude(1,0),0);near(rectFresnel(Infinity)[0],.5);const p={width:3,height:5,exposure:40},q=apertureState('rectangle',p);for(const r of q.pixels.filter((_,i)=>i%499===0))near(r.intensity,rectAmplitude((r.i+.5)/10,3)*rectAmplitude((r.j+.5)/10,5));near(q.profile[100][1],q.profile[100][2]);});
test('Zernike endpoints, parity constraints and radial orthogonality are independent physical invariants',()=>{for(let m=0;m<=8;m++)for(let n=m;n<=m+14;n+=2){near(zernikeR(m,n,1),1);near(zernikeR(m,n,0),m===0?(-1)**(n/2):0);}assert.equal(zernikeR(1,2,.5),0);for(const [m,n,k]of [[0,0,2],[0,2,4],[1,1,3],[2,2,4]]){let sum=0;const N=2000;for(let i=0;i<=N;i++){const x=i/N,w=i===0||i===N?1:i%2?4:2;sum+=w*x*zernikeR(m,n,x)*zernikeR(m,k,x);}assert.ok(Math.abs(sum/(3*N))<1e-9);}});
test('Pupil is a linear superposition and its added diameter shares the same field, including reversed angles',()=>{const s=Object.values(apertureSpecs).find(s=>s.type==='pupil'),p=apertureDefaults(s),a=apertureState(s.type,p);for(let i=0;i<=100;i+=10){near(a.profile[100+i][1],pupilValue(p,i/100,0));near(a.profile[100-i][1],pupilValue(p,i/100,Math.PI));}for(const v of a.grid.flat())near(v.point[2],25*v.w);const b={...p,a02:.4,a11:-.6};for(const [r,t]of [[0,0],[.2,1],[1,2]])near(pupilValue(b,r,t),pupilValue(p,r,t)+.4*zernikeR(0,2,r)-.6*zernikeR(1,1,r)*Math.cos(t));assert.ok(projectPupil([10,20,30]).every(Number.isFinite));});
test('Static aperture CSV exports preserve unclipped intensities and original sampling grids',()=>{for(const s of Object.values(apertureSpecs)){const p=apertureDefaults(s),csv=apertureCSV(s.type,p).trimEnd().split('\n');assert.equal(csv.length,s.type==='rectangle'?40403:s.type==='pupil'?266:s.type==='circle'?53:203);assert.deepEqual(JSON.parse(csv[0].slice(2)).parameters,p);}const s=Object.values(apertureSpecs).find(s=>s.type==='rectangle');assert.equal(apertureDefaults(s).exposure,40);});
const root=new URL('../',import.meta.url),read=f=>JSON.parse(fs.readFileSync(new URL(f,root))),current=f=>{const r=read(f);for(const [file,h]of Object.entries(r.nativeModelHashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL(file,root))).digest('hex'),h,'Stale '+f+' '+file);return r;};
test('Four aperture remasters retain distinct source/runtime/current vector UI evidence and original bytes',()=>{const a=current('docs/aperture-source-report.json'),b=current('docs/aperture-runtime-report.json'),u=current('docs/aperture-ui-report.json'),manifest=read('src/flash-manifest.json').files,catalog=read('assets/flash-catalog.json').files;for(const r of [a,b]){assert.equal(r.results.length,4);assert.ok(r.results.every(v=>v.passed&&v.comparisons>0&&v.scope&&v.fullEquivalence===false));}assert.equal(u.passed,true);assert.deepEqual(u.errors,[]);assert.equal(u.results.length,12);for(const s of Object.values(apertureSpecs)){const r=b.results.find(v=>v.id===s.id);assert.equal(r.sha256,manifest.find(v=>v.id===s.id).sha256);assert.equal(r.sha256Verified,true);assert.ok(r.controls.every(c=>c.passed));assert.ok(catalog.find(v=>v.id===s.id).nativeHref.includes('aperture-'+s.id));for(const width of [320,768,1360]){const t=u.results.find(v=>v.id===s.id&&v.width===width);for(const k of ['passed','csvMatchesState','staticHasNoFrameBar','vectorOnly','darkThemeFinite'])assert.equal(t[k],true);}}});
