import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {beamSpecs,beamState,radius,amplitude,lensTransform,fieldGrid,longitudinal,wavefront} from '../assets/beam-physics.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9*Math.max(1,Math.abs(a),Math.abs(b)),a+' / '+b);
test('Gaussian amplitude is even in r, equals 1/e at the local beam boundary, and expands symmetrically about its waist',()=>{for(const z of [0,.1,1,10,100]){const w=radius(2,5,z);near(w,radius(2,5,-z));near(amplitude(2,5,z,w)/amplitude(2,5,z,0),Math.exp(-1));near(amplitude(2,5,z,1),amplitude(2,5,z,-1));}near(radius(2,5,5),2*Math.SQRT2);});
test('Thin lens transformation preserves the incident beam width at the lens plane and Rayleigh/waist relation',()=>{for(const z of [-20,0,10,30])for(const f of [1,5,10,30]){const q=lensTransform(12,3,z,f);near(radius(3,12,z),radius(q[1],q[0],q[2]));near(q[0]/q[1]**2,12/9);}});
test('Both lens seams have continuous radius and power-normalized field amplitude',()=>{for(const type of ['focus','doubleLens']){const s=Object.values(beamSpecs).find(s=>s.type===type),p=Object.fromEntries(s.controls.map(c=>[c.key,c.value])),state=beamState(type,p);for(let i=1;i<state.segments.length;i++){const a=state.segments[i-1],b=state.segments[i];near(a.x0+a.z2*a.scale,b.x0+b.z1*b.scale);near(radius(a.w0,a.z0,a.z2),radius(b.w0,b.z0,b.z1));}const grid=fieldGrid(state);assert.ok(grid.length>5000);assert.ok(grid.every(a=>Number.isFinite(a.amplitude)&&Number.isFinite(a.phase)));}});
test('Resonator confocal branch stays finite and unstable boundaries expose no stale beam segments',()=>{const p={R1:20,R2:20,lambda:.5},a=beamState('resonator',p);assert.equal(a.stable,true);assert.equal(a.z0,10);near(a.segments[0].z1,-10);near(a.segments[0].z2,10);for(const R1 of [10,21,100]){const b=beamState('resonator',{...p,R1});assert.equal(b.stable,false);assert.deepEqual(b.segments,[]);assert.equal(b.w0,null);assert.deepEqual(fieldGrid(b),[]);}assert.equal(beamState('resonator',{R1:10,R2:10,lambda:.5}).stable,false);});
test('Beam field grid and longitudinal profile agree on the same centre samples; phasefront guards clip the segment',()=>{const s=Object.values(beamSpecs).find(s=>s.type==='shape'),state=beamState(s.type,Object.fromEntries(s.controls.map(c=>[c.key,c.value]))),profile=longitudinal(state);for(const a of fieldGrid(state).filter(a=>a.r===0&&a.x%10===0)){const q=profile.find(q=>q.x===a.x);near(a.amplitude,q.amplitude);near(a.phase,q.phase);}const b=state.segments[0];assert.deepEqual(wavefront(b,b.z1-1),[]);assert.deepEqual(wavefront(b,b.z2+1),[]);assert.equal(wavefront(b,0)[0][0],'M');});
const root=new URL('../',import.meta.url),read=f=>JSON.parse(fs.readFileSync(new URL(f,root))),current=f=>{const r=read(f);for(const [file,h]of Object.entries(r.nativeModelHashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL(file,root))).digest('hex'),h,'Stale '+f+' '+file);return r;};
test('Four Gaussian remasters have independent source and actual runtime evidence, retained originals and twelve current vector UI checks',()=>{const a=current('docs/beam-source-report.json'),b=current('docs/beam-runtime-report.json'),u=current('docs/beam-ui-report.json'),manifest=read('src/flash-manifest.json').files,catalog=read('assets/flash-catalog.json').files;for(const r of [a,b]){assert.equal(r.results.length,4);assert.ok(r.results.every(v=>v.passed&&v.comparisons>0&&v.scope&&v.fullEquivalence===false));}assert.equal(u.passed,true);assert.deepEqual(u.errors,[]);assert.equal(u.results.length,12);for(const s of Object.values(beamSpecs)){const r=b.results.find(v=>v.id===s.id);assert.equal(r.sha256,manifest.find(v=>v.id===s.id).sha256);assert.equal(r.sha256Verified,true);assert.ok(r.controls.every(c=>c.passed));assert.ok(catalog.find(v=>v.id===s.id).nativeHref.includes('beam-'+s.id));for(const width of [320,768,1360]){const t=u.results.find(v=>v.id===s.id&&v.width===width);for(const k of ['passed','csvMatchesState','staticHasNoFrameBar','vectorOnly','darkThemeFinite'])assert.equal(t[k],true);assert.deepEqual(t.drags,s.controls.filter(c=>c.axis).map(c=>c.key));}}});
