import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {circuitSpecs,connectionValues,ohmInitial,ohmControl,ohmAdvance,ohmMove,makeRandom,capacitorFrame,magneticOrbitState} from '../assets/circuit-physics.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(a),Math.abs(b)),a+' / '+b);
test('Series/parallel resistor models obey Kirchhoff current/voltage and supplied power',()=>{for(let a=1;a<=12;a++)for(let b=1;b<=12;b++){const p={value1:a,value2:b,value3:3,voltage:6},v=connectionValues('resistors',p);near(v.seriesVoltages.reduce((a,b)=>a+b),p.voltage);near(v.parallelCurrents.reduce((a,b)=>a+b),v.parallelCurrent);near(v.seriesPowers.reduce((a,b)=>a+b),6*v.seriesCurrent);near(v.parallelPowers.reduce((a,b)=>a+b),6*v.parallelCurrent);assert.ok(v.parallel<Math.min(a,b,3));}});
test('Capacitor series charges coincide, voltages sum, and parallel charge is additive',()=>{for(let a=1;a<=12;a++)for(let b=1;b<=12;b++){const p={value1:a,value2:b,value3:3,voltage:6},v=connectionValues('capacitors',p);near(v.seriesVoltages.reduce((a,b)=>a+b),6);for(let i=0;i<3;i++)near([a,b,3][i]*v.seriesVoltages[i],v.seriesCharge);near(v.parallelCharges.reduce((a,b)=>a+b),v.parallelCharge);}assert.equal(capacitorFrame(false,1000),1);assert.equal(capacitorFrame(true,0),2);assert.equal(capacitorFrame(true,18),20);});
test('Circular magnetic force does no work and velocity stays tangent through two turns',()=>{for(let n=0;n<=720;n++){const z=magneticOrbitState(n);near(z.vx*z.fx+z.vy*z.fy,0);near(z.x*z.x+z.y*z.y,1);near(z.fx,-z.x);near(z.fy,-z.y);}near(magneticOrbitState(0).y,-1);near(magneticOrbitState(90).x,1);});
test('Scattering preserves source 0.8 kinetic-energy ratio, reflected transverse speed and outlet reinjection',()=>{const start={x:9.99,y:0,vx:1,vy:0},stream=[0,.8,.9],a=ohmMove(start,1,5,()=>stream.shift());assert.equal(a.collision,true);near(a.vx*a.vx+a.vy*a.vy,.8*1.1*1.1);const b=ohmMove({x:20,y:51,vx:2,vy:3},5,4,()=>1);near(b.y,49);near(b.vy,-3);near(b.vx,2);const c=ohmMove({x:299.99,y:0,vx:10,vy:1},5,4,()=>.6);assert.equal(c.passed,1);near(c.x,.01);near(c.vx,0);near(c.y,9);near(c.vy,1);});
test('Seeded ensemble replays exactly; slider changes preserve particle state and restart only source measurement scope',()=>{let a=ohmInitial(4),b=ohmInitial(4);for(let i=0;i<600;i++){a=ohmAdvance(a);b=ohmAdvance(b);}assert.deepEqual(a,b);assert.ok(a.totalPassed>0&&a.collisions>0&&a.marked[50]);const c=ohmControl(a,'voltage',7);assert.deepEqual(c.particles,a.particles);near(c.current,a.current);assert.equal(c.dataCounter,0);assert.deepEqual(c.measurements,a.measurements);const d=ohmControl(a,'crosssection',2);assert.ok(d.marked.every(v=>!v));assert.ok(d.measurements.every(v=>!v));const e=ohmControl({...a,autoCounter:2500},'auto',true);assert.equal(e.autoCounter,2500);const f=ohmAdvance(e);near(f.voltage,1.1);assert.equal(f.autoCounter,0);assert.equal(f.rate,50);});
const root=new URL('../',import.meta.url),read=f=>JSON.parse(fs.readFileSync(new URL(f,root))),current=f=>{const r=read(f);for(const [file,hash]of Object.entries(r.nativeModelHashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL(file,root))).digest('hex'),hash,'Stale '+f+' '+file);return r;};
test('All five circuit remasters retain current independent-source, real-runtime and 15 responsive native checks',()=>{const a=current('docs/circuit-source-report.json'),b=current('docs/circuit-runtime-report.json'),ui=current('docs/circuit-ui-report.json'),manifest=read('src/flash-manifest.json').files,catalog=read('assets/flash-catalog.json').files;assert.equal(Object.keys(circuitSpecs).length,5);for(const r of [a,b]){assert.equal(r.results.length,5);assert.ok(r.results.every(v=>v.passed&&v.comparisons>0&&v.scope&&v.fullEquivalence===false));}assert.equal(ui.passed,true);assert.equal(ui.results.length,15);assert.deepEqual(ui.errors,[]);for(const s of Object.values(circuitSpecs)){const runtime=b.results.find(v=>v.id===s.id);assert.equal(runtime.sha256,manifest.find(v=>v.id===s.id).sha256);assert.equal(runtime.sha256Verified,true);assert.ok(runtime.controls.every(v=>v.passed));assert.ok(catalog.find(v=>v.id===s.id).nativeHref.includes('circuit-'+s.id));for(const width of [320,768,1360]){const u=ui.results.find(v=>v.id===s.id&&v.width===width);assert.equal(u.passed,true);assert.equal(u.darkThemeFinite,true);if(s.animated)for(const k of ['actualSceneMotion','pauseStopsMotion','fixedProgressAndEndReplay','sharedNumericalState'])assert.equal(u[k],true,s.type+' '+width+' '+k);if(s.type==='ohmslaw')assert.equal(u.csvMatchesState,true);}}});
