import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {diffractionSpecs,fresnel,diffractionState,phasorState,slitRays,zoneScales} from '../assets/diffraction-physics.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9*Math.max(1,Math.abs(a),Math.abs(b)),a+' / '+b);
test('Fresnel integration is odd at both source precisions and exposes exact infinite endpoints',()=>{for(const coarse of [false,true])for(const w of [.01,.05,1,2.35,5,20]){const a=fresnel(w,coarse),b=fresnel(-w,coarse);near(a[0],-b[0]);near(a[1],-b[1]);}assert.deepEqual(fresnel(Infinity),[.5,.5]);assert.deepEqual(fresnel(-Infinity),[-.5,-.5]);near(fresnel(0)[0],0);near(fresnel(0)[1],0);assert.notDeepEqual(fresnel(2.35,true),fresnel(2.35,false));});
test('Knife edge intensity at its origin is one quarter; zero slit has zero amplitude for every exposure',()=>{near(diffractionState(0,2,true).intensity,.25);for(const w of [-12,0,2,12])for(const e of [1,5,25,125,625]){const q=diffractionState(w,0,false,e);near(q.intensity,0);near(q.amplitude,0);assert.equal(q.brightness,0);}for(const width of [.05,2,20]){const a=diffractionState(-3-width/2,width),b=diffractionState(3-width/2,width);near(a.intensity,b.intensity);near(a.amplitude**2,a.intensity);}});
test('Finite phasors cancel at a full turn and constructively add at zero phase; rounded zero angle remains defined',()=>{for(let n=2;n<=30;n++){const a=phasorState(n,0),b=phasorState(n,360);near(a.intensity,1);assert.equal(a.percent,100);assert.equal(a.component,Math.floor(.5+1000/n)/10);assert.ok(b.intensity<1e-13);assert.equal(b.percent,0);assert.equal(b.resultAngle,0);assert.equal(a.points.length,n+1);}});
test('Slit path differences change sign under angle reflection and scale inversely with divisions',()=>{for(const n of [2,10,30])for(const a of [0,10,30]){near(slitRays(n,a).pathDifference,-slitRays(n,-a).pathDifference);near(slitRays(n,a).pathDifference*n,slitRays(2,a).pathDifference*2);assert.equal(slitRays(n,a).boxes.length,n);}});
test('Zone display excludes the exact 300 threshold and respects wavelength scaling',()=>{assert.equal(zoneScales(500)[35],0);assert.ok(zoneScales(500)[34]>0);assert.equal(zoneScales(500).filter(Boolean).length,35);assert.ok(zoneScales(400).filter(Boolean).length>zoneScales(700).filter(Boolean).length);near(zoneScales(500)[3]/zoneScales(500)[0],2);});
const root=new URL('../',import.meta.url),read=f=>JSON.parse(fs.readFileSync(new URL(f,root))),current=f=>{const r=read(f);for(const [file,h]of Object.entries(r.nativeModelHashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL(file,root))).digest('hex'),h,'Stale '+f+' '+file);return r;};
test('Six diffraction remasters retain original hashes, explicit finite scopes and 18 current native UI records',()=>{const a=current('docs/diffraction-source-report.json'),b=current('docs/diffraction-runtime-report.json'),u=current('docs/diffraction-ui-report.json'),manifest=read('src/flash-manifest.json').files,catalog=read('assets/flash-catalog.json').files;for(const r of [a,b]){assert.equal(r.results.length,6);assert.ok(r.results.every(v=>v.passed&&v.comparisons>0&&v.scope&&v.fullEquivalence===false));}assert.equal(u.passed,true);assert.deepEqual(u.errors,[]);assert.equal(u.results.length,18);for(const s of Object.values(diffractionSpecs)){const r=b.results.find(v=>v.id===s.id);assert.equal(r.sha256,manifest.find(v=>v.id===s.id).sha256);assert.equal(r.sha256Verified,true);assert.ok(r.controls.every(c=>c.passed));assert.ok(catalog.find(v=>v.id===s.id).nativeHref.includes('diffraction-'+s.id));for(const width of [320,768,1360]){const t=u.results.find(v=>v.id===s.id&&v.width===width);assert.equal(t.passed,true);assert.equal(t.csvMatchesState,true);if(s.animated)for(const k of ['actualSceneMotion','pauseStopsMotion','sharedStateAndSeek','fixedBottomProgressAndReplay'])assert.equal(t[k],true);else assert.equal(t.staticHasNoFrameBar,true);}}});
