import test from'node:test';import assert from'node:assert/strict';import{generalBatch50bParticlesSpecs,particlesInitial,particlesAdvance,particlesState,particlesCSV,particleBounce}from'../assets/general-batch50b-particles-physics.mjs';import{generalBatch50bDynamicsSpecs,dynamicsState,dynamicsCSV,chainInitial,chainAdvance,chainEnergy,longitudinalAdvance,gridAdvance,ljPotential,dominoTorque,reflectedPulse,phasorState,projectileState}from'../assets/general-batch50b-dynamics-physics.mjs';
test('single-wall reflection preserves 2D speed and original 3D x-fed-z defect',()=>{assert.deepEqual(particleBounce(9,3,0,10),{x:8,v:-3,hit:1});const s=Object.values(generalBatch50bParticlesSpecs).find(s=>s.type==='gas'),b=particlesInitial(s,2026);let q=b;for(let n=0;n<1000;n++)q=particlesAdvance(s,q);q.forEach((p,i)=>assert.ok(Math.abs(Math.hypot(p.vx,p.vy)-Math.hypot(b[i].vx,b[i].vy))<1e-10));const s3=Object.values(generalBatch50bParticlesSpecs).find(s=>s.type==='gas3d'),r=particlesAdvance(s3,[{x:0,y:0,z:0,vx:2,vy:3,vz:7}])[0];assert.equal(r.z,2);});
test('seed restoration and current CSV',()=>{for(const s of Object.values(generalBatch50bParticlesSpecs)){assert.deepEqual(particlesInitial(s,18),particlesInitial(s,18));assert.notDeepEqual(particlesInitial(s,18),particlesInitial(s,19));const q=particlesState(s,{seed:2026},25);assert.ok(particlesCSV(q).includes('25,0,'));}});
test('spring chain fixed right boundary, driver and changing energy',()=>{for(let count=1;count<=10;count++){const p={count,omega:4},a=chainInitial(p);let b=a;for(let i=0;i<200;i++)b=chainAdvance(b,p);assert.equal(b.x.at(-1),a.x.at(-1));assert.ok(chainEnergy(b)>0);assert.ok(b.x.slice(1,-1).some((x,i)=>Math.abs(x-a.x[i+1])>1e-5));}});
test('inverse-distance symmetric equilibrium and fixed membrane edges',()=>{assert.deepEqual(longitudinalAdvance({x:200,v:0}),{x:200,v:0});const y=Array.from({length:9},()=>Array(9).fill(0));y[4][4]=80;const b=gridAdvance({y,v:y.map(r=>r.map(()=>0))});assert.ok(b.y[4][4]<80);assert.equal(b.y[0][4],0);assert.equal(b.y[8][4],0);assert.ok(b.y[4][3]>0);});
test('Lennard-Jones minimum and far-distance limit',()=>{const p={Uo:50,Ro:.6};assert.ok(Math.abs(ljPotential(0,0,.6,0,p)+50)<1e-9);assert.ok(ljPotential(0,0,.3,0,p)>0);assert.ok(Math.abs(ljPotential(0,0,600,0,p))<1e-10);});
test('domino no-contact and signed pulse reflection',()=>{assert.equal(dominoTorque(85,0,0),0);const fixed=reflectedPulse(0,45,false),free=reflectedPulse(0,45,true);assert.equal(fixed[0],0);assert.ok(free[0]!==0);});
test('phasor opposite phase cancellation and projectile center conservation',()=>{const q=phasorState({len1:100,len2:100,omega1:0,omega2:0,phase:180},10);assert.ok(Math.hypot(...q.sum)<1e-5);const p={rotSpeed:1000,speed:.2,angle:1,object:'bomb'},a=projectileState(p,300);assert.equal(a.screenX,40+50*a.x);assert.ok(a.frag>0);});
test('all13 finite actual geometry states and visible current CSV',()=>{for(const s of Object.values(generalBatch50bDynamicsSpecs)){const p={...Object.fromEntries(s.controls.map(c=>[c.key,c.value])),object:s.type==='pulse'?'triangle':'bat',free:false,driven:true,mode:'vibration'},a=dynamicsState(s,p,0),b=dynamicsState(s,p,20);assert.notDeepEqual(a,b);assert.ok(!/NaN|Infinity|undefined/.test(JSON.stringify(b)));assert.ok(dynamicsCSV(b).includes('20'));}});

test('analytic string modes export only quantities actually computed for that mode',()=>{const s=Object.values(generalBatch50bDynamicsSpecs).find(s=>s.type==='string'),p={...Object.fromEntries(s.controls.map(c=>[c.key,c.value])),mode:'travelling',free:false,driven:false},q=dynamicsState(s,p,10),csv=dynamicsCSV(q);assert.equal(csv.split('\n')[0],'step,index,height');assert.equal(+csv.split('\n')[26].split(',')[2],q.y[25]);});
