import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {generalNextPhasorSpecs,phasorState,coefficient,fourierValue,phasorCSV} from '../assets/general-next-phasor-physics.mjs';
const spec=t=>Object.values(generalNextPhasorSpecs).find(s=>s.type===t),params=s=>({...Object.fromEntries(s.controls.map(c=>[c.key,c.value])),mode:0,order:1,direction:true,selected:0,selectedY:0,pickedPhase:50});
test('opposing equal phasors cancel and aligned phasors add',()=>{const s=spec('phasor7'),p={...params(s),A1:50,A2:50,phase:180};const q=phasorState(s,p,.41);assert.ok(Math.hypot(...q.sum)<1e-10);assert.ok(q.meta.amplitude<1e-10);p.phase=0;assert.ok(Math.abs(phasorState(s,p,.41).meta.amplitude-100)<1e-10);});
test('phasor3 sum exactly follows the displayed wave at selected position',()=>{const s=spec('phasor3'),p={...params(s),selected:200};for(const direction of [true,false]){p.direction=direction;for(const t of [0,.17,1.83]){const q=phasorState(s,p,t);assert.ok(Math.abs(q.waves[2][100][1]-q.sum[1])<1e-10);}}});
test('standing phasors retain fixed nodes rather than travelling wave',()=>{const s=spec('phasor5');for(const t of [.15,.89]){const q=phasorState(s,params(s),t);assert.ok(Math.abs(q.grid[0].v[1])<1e-10);q.grid.forEach((v,i)=>assert.ok(Math.abs(v.v[1]-45*Math.sin(i*20/50)*Math.sin(-10*t))<1e-10));}});
test('symmetric two source distances produce zero additional phase',()=>{const s=spec('phasor6'),p={...params(s),selected:300,selectedY:175,phase:0};const q=phasorState(s,p,.31);assert.equal(q.meta.r1,q.meta.r2);assert.equal(q.meta.phaseDifference,0);assert.ok(Math.abs(Math.hypot(...q.sum)-80)<1e-10);});
test('Fourier square odd harmonic, convergence away from discontinuity',()=>{assert.equal(coefficient(0,2).a,0);assert.equal(coefficient(0,3).a,400/Math.PI/3);assert.ok(Math.abs(fourierValue(0,99,50)-75)<1);});
test('CSV contains current vector and history samples',()=>{const s=spec('phasor4'),q={...phasorState(s,params(s),.37),history:[[10,20],[11,21]]};const csv=phasorCSV(q);assert.ok(csv.includes('0.37,history1,11,21'));assert.ok(!csv.includes('NaN'));});
test('all eight original independent numerical source checks pass with matching model hashes',()=>{const r=JSON.parse(fs.readFileSync(new URL('../docs/general-next-phasor-source-report.json',import.meta.url)));assert.equal(r.files,8);assert.ok(r.results.every(s=>s.passed&&!s.originalRuntimeVerified));for(const [f,sha]of Object.entries(r.nativeModelHashes)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('../'+f,import.meta.url))).digest('hex'),sha);}});
