import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import{diffractionAmplitude,beamValue,besselJ1,slitFactor,fft,transform1D,transform2D,propagationInitial,propagate,aperturePass,cieValue,reflectionWaves,transverseBeam}from'../assets/legacy-optics-physics.mjs';
const specs=JSON.parse(fs.readFileSync(new URL('../src/legacy-optics.json',import.meta.url)));
const close=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<=e*(1+Math.abs(b)),`${a} != ${b}`);
test('legacy optics manifest maps fourteen actual Java programs, not SWF duplicates',()=>{assert.equal(specs.length,14);assert.equal(new Set(specs.map(s=>s.id)).size,14);for(const s of specs){assert.equal(s.provenance.format,'Java applet');assert.match(s.provenance.archiveSHA256,/^[a-f0-9]{64}$/);assert.ok(s.lessonId.startsWith('5-'));for(const p of s.parameters)assert.ok(p.min<=p.value&&p.value<=p.max);}});
test('diffraction finite center, symmetry and first zeros',()=>{for(const [kind,p,x]of[['single',{wavelength:500,width:1},Math.PI/4],['many',{wavelength:500,spacing:2,ratio:.5,count:2},Math.PI/4],['rectangle',{wavelength:500,width:1,height:1.5},Math.PI]]){close(diffractionAmplitude(kind,p,0),1);close(diffractionAmplitude(kind,p,x),0);for(let k=0;k<80;k++)close(diffractionAmplitude(kind,p,k*.23)**2,diffractionAmplitude(kind,p,-k*.23)**2);}close(diffractionAmplitude('circular',{wavelength:500,radius:1},0),1);close(diffractionAmplitude('circular',{wavelength:500,radius:1},3.831705970),0,1e-8);});
test('Bessel and slit values match separately executed original Java math',()=>{close(besselJ1(1),.44005058574493355);close(besselJ1(5),-.3275791375914646);close(slitFactor(.5,30),.045212988447963606);for(let n=1;n<=30;n++)close(slitFactor(Math.PI,n),n%2?1:-1);});
test('complex Gaussian field and intensity satisfy original Rayleigh law',()=>{const p={w0:1,z0:2};close(beamValue('gaussian',p,0,0,2).intensity,.5);close(beamValue('gaussian',p,1,0,0).intensity,Math.exp(-2));for(let i=0;i<100;i++){const b=beamValue('gaussian',p,(i-50)/23,.3,i/40);close(b.real**2+b.imag**2,b.intensity);}const e=beamValue('elliptic',{wx0:.8,wy0:1.2,lambda:1.4,delta:.4},-.95,-.65,-.96);close(e.intensity,.07879693766043319);});
test('Hermite modes preserve parity and nodes',()=>{const p={w0:1,z0:2.4,m:2,n:3};close(beamValue('hermite',p,.8,0,0).amplitude,0);const a=beamValue('hermite',p,.8,.4,.8),b=beamValue('hermite',p,-.8,-.4,.8);close(a.intensity,b.intensity);close(a.amplitude,-b.amplitude);});
test('FFT forward-inverse round trip and Parseval',()=>{const a=Float64Array.from({length:256},(_,i)=>Math.sin(i*.31)+.7*Math.cos(i*.13)),f=fft(a),v=fft(f.re,f.im,true);for(let i=0;i<a.length;i++){close(a[i],v.re[i]);close(v.im[i],0);}close(a.reduce((s,v)=>s+v*v,0),f.re.reduce((s,v,i)=>s+(v*v+f.im[i]**2)/a.length,0));});
test('FFT original location/offset controls affect complex phase and zero frequency',()=>{const base=transform1D({shape:1,xScale:5,position:0,offset:0}),shift=transform1D({shape:1,xScale:5,position:10,offset:0}),offset=transform1D({shape:1,xScale:5,position:0,offset:2});close(base.power[256],shift.power[256],1e-8);close(offset.re[256]-base.re[256],102.4);assert.ok(Math.abs(shift.im[260])>1e-4);for(let shape=0;shape<=11;shape++)assert.ok(transform1D({shape,xScale:5,position:0,offset:0,seed:1}).power.every(Number.isFinite));});
test('2D diffraction is the Fourier transform of each actual aperture',()=>{for(let shape=0;shape<=12;shape++){const f=transform2D({shape,xScale:5,yScale:5,rotation:30,seed:1},128);assert.ok(f.power.every(Number.isFinite));const sum=f.aperture.reduce((a,b)=>a+b,0);close(f.power[128*64+64],sum*sum);}});
test('propagation evolves all four implemented modes, conserves power and supports aperture turns',()=>{for(let shape=0;shape<=3;shape++){const s=propagationInitial(shape,50),a=propagate(s,0),b=propagate(s,800),sum=w=>w.power.reduce((a,b)=>a+b,0);close(sum(a),sum(b),1e-9);assert.ok(Math.abs(a.power[522]-b.power[522])>1e-4);const filtered=propagate(aperturePass(b,100),0);for(let i=0;i<1024;i++)if(i<=462||i>=562)close(filtered.power[i],0,1e-8);assert.ok(filtered.power.every(Number.isFinite));}});
test('CIE source table interpolation, boundary and NTSC conversion preserve negative values',()=>{close(cieValue(555)[1],1);const a=cieValue(550),b=cieValue(555),half=cieValue(552.5);for(let k=0;k<3;k++)close(half[k],(a[k]+b[k])/2);assert.deepEqual(cieValue(830),[0,0,0]);assert.ok(cieValue(500,true)[0]<0);});
test('reflection phase produces a node at a phase-reversing boundary',()=>{for(let t=0;t<100;t++)close(reflectionWaves(525,t,180).resultant,0);close(reflectionWaves(525,20,0).resultant,2*reflectionWaves(525,20,0).incident);assert.ok(Math.abs(reflectionWaves(100,0,0).resultant-reflectionWaves(100,20,0).resultant)>.1);});

test('standalone Hermite transverse modes preserve original radius, nodes and complex power',()=>{const p={m:0,n:0,z:0};close(transverseBeam(p,0,0).w,50/Math.PI);close(transverseBeam(p,0,0).intensity,1);close(transverseBeam(p,50/Math.PI,0).amplitude,Math.exp(-(1.414**2)/2));for(let m=0;m<=5;m++)for(let n=0;n<=5;n++){const p={m,n,z:50},b=transverseBeam(p,3,7);close(b.real**2+b.imag**2,b.intensity);assert.ok(Number.isFinite(b.phase));}close(transverseBeam({m:1,n:0,z:0},0,10).intensity,0);});
