import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as P from '../assets/legacy-quantum-modern-physics.mjs';
const ref=JSON.parse(fs.readFileSync(new URL('../docs/legacy-quantum-modern-reference.json',import.meta.url)));const close=(a,b,tol=3e-11)=>assert.ok(Math.abs(a-b)<=tol*Math.max(1,Math.abs(b)),`${a} ≠ ${b}`);
for(const kind of ['blackbody','resonant1','resonant2','bohr','relativity','fft','potential1','hydrogen','cloud'])test(`Original JVM oracle ${kind}`,()=>{for(const q of ref.filter(q=>q.kind===kind)){if(kind==='blackbody')close(P.blackbodySpectrum(q.w,q.T,q.rayleigh),q.value);if(kind==='resonant1')close(P.resonant1(q.n,q.x,q.t),q.value);if(kind==='resonant2')close(P.resonant2(q.nx,q.ny,133,177,q.t),q.value);if(kind==='bohr'){const e=P.bohrElectron(q.n,.73,q.clockwise,q.t);close(e.x,q.x);close(e.y,q.y);}if(kind==='relativity')close(P.relativisticPoint(100,50,400,q.v,q.t).x,q.value);if(kind==='cloud')close(P.hydrogenCloudValue(q.n,q.l,q.m,2.3,1.1),q.value);if(kind==='hydrogen'){const r=2.3,t=.7,phi=.9,z=P.hydrogenEigen(q.n,q.l,q.m,r*Math.sin(t)*Math.cos(phi),r*Math.sin(t)*Math.sin(phi),r*Math.cos(t));close(z.re,q.re);close(z.im,q.im);}if(kind==='fft'){const f=P.complexField(64);for(let i=0;i<64;i++){f.re[i]=Math.sin(i*.31);f.im[i]=Math.cos(i*.07);}const g=P.centeredFFT(f,q.inverse);for(const [i,r,s]of q.samples){close(g.re[i],r);close(g.im[i],s);}}if(kind==='potential1'){const m=P.buildPotential1D({type:q.type});P.stepPotential1D(m,q.step);for(const [i,r,s]of q.samples){close(m.field.re[i],r);close(m.field.im[i],s);}}}});
test('Original 2D ADI kernel, all independently sampled matrix corners',()=>{for(const q of ref.filter(q=>q.kind==='potential2kernel')){const N=q.N,f=P.complexField(N*N),exp=P.complexField(N*N);for(let x=0;x<N;x++)for(let y=0;y<N;y++){const j=x*N+y,a=x*.3+y*.5,A=Math.exp(-(x*x+y*y)/20),v=q.po*(x-y)**2/N**2;f.re[j]=A*Math.cos(a);f.im[j]=A*Math.sin(a);exp.re[j]=Math.cos(-v/65536);exp.im[j]=Math.sin(-v/65536);} // expose the same factorization through a zero-potential original-size model
 const template=P.buildPotential2D('potential-2d');const m={N,field:f,exp,lu:{a:P.complexField(N),b:P.complexField(N)},time:0,kind:'kernel'};for(let i=0;i<N;i++){let r=-2,s=4;if(i){const a=m.lu.a.re[i-1],b=m.lu.a.im[i-1],d=a*a+b*b;r-=a/d;s+=b/d;}m.lu.a.re[i]=r;m.lu.a.im[i]=s;m.lu.b.re[i]=r/(r*r+s*s);m.lu.b.im[i]=-s/(r*r+s*s);}P.stepPotential2D(m,2);for(const [x,y,r,s]of q.samples){close(f.re[x*N+y],r);close(f.im[x*N+y],s);}}});
test('Free packets: all shapes, boundaries, classical switches and integer input extremes remain finite',()=>{for(const kind of ['free-particle','free-box','free-ring'])for(let shape=0;shape<6;shape++)for(const k0 of [-10,100])for(const width of [1,kind==='free-particle'?50:40])for(const fixed of [false,true])for(const classical of [false,true]){const m=P.buildFree1D(kind,{shape,k0,width,fixed,classical}),f=P.free1DAt(m,33);assert.ok(f.re.every(Number.isFinite));assert.ok(f.im.every(Number.isFinite));}});
test('Potential 2D all 10 potential choices, symmetry and extreme initial controls evolve',()=>{for(let type=0;type<10;type++){const m=P.buildPotential2D('potential-2d',{type});P.stepPotential2D(m,2);assert.ok(m.field.re.every(Number.isFinite));}for(const symmetric of [false,true]){const m=P.buildPotential2D('particle-fd',{symmetric});P.stepPotential2D(m,200);for(let x=0;x<128;x+=7)for(let y=0;y<128;y+=7){close(m.field.re[x*128+y],(symmetric?1:-1)*m.field.re[y*128+x],1e-8);}}});
const packets=JSON.parse(fs.readFileSync(new URL('../docs/legacy-quantum-packet-reference.json',import.meta.url)));
test('Original applets: six 1D shapes × defaults/edge inputs × classical/boundary cases × three times',()=>{for(const q of packets.filter(q=>q.kind!=='free2D')){const kind={freeParticle:'free-particle',freeBox:'free-box',freeRing:'free-ring'}[q.kind],m=P.buildFree1D(kind,{shape:q.shape,k0:q.k,width:q.width,fixed:q.fixed,classical:q.classical}),f=P.free1DAt(m,q.time);for(const [j,r,s]of q.samples){close(f.re[j],r,3e-9);close(f.im[j],s,3e-9);}}});
test('Original full 512×256 FFT2D vs separable implementation: all six shapes, both boundary choices and three times',()=>{for(const q of packets.filter(q=>q.kind==='free2D')){const m=P.buildFree2D({shape:q.shape,fixed:q.fixed}),f=P.free2DAt(m,q.time);for(const [x,y,r,s]of q.samples){close(f.re[x*128+y],r,3e-9);close(f.im[x*128+y],s,3e-9);}}});

const potentialRefs=JSON.parse(fs.readFileSync(new URL('../docs/legacy-quantum-potential-reference.json',import.meta.url)));
test('Actual 128² source applets: four quantum models, 10 potentials, both particle symmetries, initial boundaries and evolved arrays',()=>{for(const q of potentialRefs){const kind={twoDimHarmonicOsc:'harmonic-2d',twoDimQuantum:'potential-2d',twoParticleDI:'particle-di',twoParticleFD:'particle-fd'}[q.kind],v=q.variant,p={x0:v===0?5:v===1?4:16,y0:kind==='particle-fd'?15:kind==='potential-2d'?5:4,kx:v===0?(kind==='particle-fd'?0:10):v===1?-40:40,ky:kind==='potential-2d'?10:0,uncertainty:v===0?25:v===1?15:50,uncertaintyY:25,K:v===1?0:v===2?200:100,C:100,type:q.type,symmetric:q.symmetric};const m=P.buildPotential2D(kind,p);P.stepPotential2D(m,q.step);for(const[x,y,r,s]of q.samples){close(m.field.re[x*128+y],r,3e-9);close(m.field.im[x*128+y],s,3e-9);}}});
