import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {originalWave,soundState,originalSpectrum,originalFourier,sourceSignal} from '../assets/legacy-general-sound-physics.mjs';
import {soundControls} from '../assets/legacy-general-sound.mjs';
import {thermoConfigs,thermoInitial,thermoStep,thermoSnapshot,vwPotential,pairForce,collisionTime,elasticCollision} from '../assets/legacy-general-thermo-physics.mjs';
import {thermoControls} from '../assets/legacy-general-thermo.mjs';
const finite=v=>typeof v==='number'?Number.isFinite(v):v&&typeof v==='object'?Object.values(v).every(finite):true;
const specs=JSON.parse(fs.readFileSync(new URL('../src/legacy-general.json',import.meta.url))),near=(a,b)=>assert.ok(Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(b)),`${a} versus ${b}`),defaults=c=>Object.fromEntries([...c.ranges.map(r=>[r.key,r.value]),...c.selects.map(([k,l,opts,v])=>[k,v??0]),...c.checks.map(([k,l,v])=>[k,v])]);
test('Original JVM waveform bytecode 432 values',()=>{const oracle=JSON.parse(fs.readFileSync(new URL('../docs/legacy-general-next-oracle.json',import.meta.url)));assert.equal(oracle.waveform.rows.length,432);for(const [k,f,a,t,y] of oracle.waveform.rows){near(originalWave(k,f,a,t),y);}});
test('Original JVM VWpotential bytecode 252 values including negative charge',()=>{const oracle=JSON.parse(fs.readFileSync(new URL('../docs/legacy-general-next-oracle.json',import.meta.url)));assert.equal(oracle.potential.rows.length,252);for(const [k,u,r,d,y] of oracle.potential.rows){near(vwPotential(u,r,d,k),y);}});
test('Hard collision conserves 3D momentum and energy',()=>{const a={x:0,y:0,z:0,vx:3,vy:1,vz:2,r:.1,mass:1},b={x:.2,y:0,z:0,vx:-1,vy:2,vz:0,r:.1,mass:2},total=()=>[...['vx','vy','vz'].map(k=>a.mass*a[k]+b.mass*b[k]),[a,b].reduce((v,q)=>v+q.mass*(q.vx*q.vx+q.vy*q.vy+q.vz*q.vz)/2,0)],before=total();elasticCollision(a,b,3);total().forEach((v,i)=>near(v,before[i]));});
test('Soft spring force and pair antisymmetry',()=>{const a={x:0,y:0,r:.1,charge:0},b={x:.15,y:0,r:.1,charge:0};near(pairForce(a,b).x,-2000);near(pairForce(b,a).x,2000);near(pairForce(a,b).potential,50);});
test('Collision root and zero relative velocity',()=>{near(collisionTime({x:0,y:0,vx:1,vy:0,r:.1},{x:1,y:0,vx:0,vy:0,r:.1}),.8);assert.equal(collisionTime({x:0,y:0,vx:1,vy:0,r:.1},{x:1,y:0,vx:1,vy:0,r:.1}),Infinity);});
test('FFT source scaling and Fourier coefficients',()=>{const y=originalSpectrum([1,1,1,1]);near(y[0],8);near(y[1],0);near(originalFourier(0,1,100),4*45/Math.PI);near(originalFourier(2,0,0),90/Math.PI);near(sourceSignal(4,7,{frequency:500}),1.75);});
for(const spec of specs.filter(s=>s.kind==='thermo-legacy'))test('thermo '+spec.model+' default and each slider endpoints remain finite',()=>{const c=thermoControls(spec.model),d=defaults(c),cases=[d,...c.ranges.flatMap(r=>[{...d,[r.key]:r.min},{...d,[r.key]:r.max}])];for(const p of cases){const s=thermoInitial(spec.model,p);thermoStep(s,5);const str=JSON.stringify(thermoSnapshot(s));assert.ok(finite(thermoSnapshot(s)),'nonfinite '+spec.model+JSON.stringify(p));assert.equal(s.frame,5);assert.ok(s.time>0);}});
for(const spec of specs.filter(s=>s.kind==='sound-legacy'))test('sound '+spec.model+' each slider endpoints stay finite',()=>{const c=soundControls(spec.model),d=defaults(c),cases=[d,...c.ranges.flatMap(r=>[{...d,[r.key]:r.min},{...d,[r.key]:r.max}])];for(const p of cases)for(const f of [0,1,80,501,999]){const s=soundState(spec.model,p,f);assert.ok(finite(s),'nonfinite '+spec.model+JSON.stringify(p));}});

function products(groups){return groups.reduce((acc,g)=>acc.flatMap(a=>g.map(v=>({...a,...v}))),[{}]);}
for(const spec of specs.filter(s=>s.kind==='thermo-legacy'))test('thermo '+spec.model+' all finite option combinations and continuous corners',()=>{const c=thermoControls(spec.model),d=defaults(c),discrete=products([...c.selects.map(([k,l,opts])=>opts.map(v=>({[k]:v}))),...c.checks.map(([k])=>[{[k]:false},{[k]:true}])]),corners=products(c.ranges.map(r=>[{[r.key]:r.min},{[r.key]:r.max}]));for(const opts of discrete)for(const corner of corners){const p={...d,...opts,...corner},s=thermoInitial(spec.model,p);thermoStep(s,1);assert.ok(finite(thermoSnapshot(s)),JSON.stringify(p));}});
test('MIDI all channel/program/checkbox combinations are finite (65536)',()=>{const c=soundControls('midisound.midi'),d=defaults(c),cases=products([...c.selects.map(([k,l,opts])=>opts.map(v=>({[k]:v}))),...c.checks.map(([k])=>[{[k]:false},{[k]:true}])]);assert.equal(cases.length,65536);for(const opts of cases)assert.ok(finite(soundState('midisound.midi',{...d,...opts},123)));});
