// Run against private original .class caches; no rewritten source is used as an oracle.
import java.io.*;import java.net.*;import java.lang.reflect.*;
class LegacyOpticsRestReference {
 static Object field(Object o,String s)throws Exception{Field f=o.getClass().getDeclaredField(s);f.setAccessible(true);return f.get(o);}
 static Class<?> load(URLClassLoader l,String s)throws Exception{return Class.forName(s,true,l);}
 static Object point(Class<?> c,double x,double y,double dir)throws Exception{Constructor<?> con=c.getDeclaredConstructor(double.class,double.class,double.class);con.setAccessible(true);return con.newInstance(x,y,dir);}
 static double number(Object o,String name)throws Exception{Field f=o.getClass().getField(name);f.setAccessible(true);return f.getDouble(o);}
 public static void main(String[] args)throws Exception{
  URLClassLoader l=new URLClassLoader(new URL[]{new File(args[1]).toURI().toURL()});PrintWriter w=new PrintWriter(args[2]);
  if(args[0].equals("lens")){Class<?> lens=load(l,"ThinLens"),ep=load(l,"ePoint");Constructor<?> con=lens.getConstructor(int.class,double.class,double.class,double.class,double.class,double.class);Method attr=lens.getMethod("setAttribute",int.class,int.class,int.class),ray=lens.getMethod("rayTrace",ep),dist=lens.getMethod("distance",ep);for(int kind=0;kind<5;kind++)for(int mode=0;mode<3;mode++)for(int i=0;i<180;i++){double angle=(i%9-4)*.21,cx=20,cy=-7,dir=(i%4)*Math.PI/4,length=50,f=(i%2==0?1:-1)*80,x=(i%3-1)*150,y=i-90;Object c=con.newInstance(kind,cx,cy,dir,length,f);attr.invoke(c,1,mode,3);Object p=point(ep,x,y,angle),q=ray.invoke(c,p);w.printf(java.util.Locale.ROOT,"%d,%d,%d,%.17g,%.17g,%.17g,%.17g%n",kind,mode,i,number(q,"x"),number(q,"y"),number(q,"dir"),dist.invoke(c,p));}}
  if(args[0].equals("index")){Class<?> c=load(l,"rIndex"),ep=load(l,"ePoint"),rt=load(l,"raytrace1");Constructor<?> con=c.getDeclaredConstructor(int.class,double.class);con.setAccessible(true);Method n=c.getMethod("n",double.class,double.class);n.setAccessible(true);for(int kind:new int[]{1,2,3,4,5,6,7,8,9,15,16,17,21,22,23,24}){Object o=con.newInstance(kind,1.5);for(String k:new String[]{"par1","par2","par3"}){Field f=c.getField(k);f.setAccessible(true);f.setDouble(o,k.equals("par1")?250:k.equals("par2")?25:2);}for(int i=0;i<1000;i++){double x=(i%40)*15.5,y=(i/40)*17.5;w.printf(java.util.Locale.ROOT,"I,%d,%d,%.17g%n",kind,i,n.invoke(o,x,y));}Constructor<?> cr=rt.getDeclaredConstructor(c,int.class);cr.setAccessible(true);Object ray=cr.newInstance(o,3);Method next=rt.getDeclaredMethod(kind>=21?"NextBy2Beam":"NextBy1Beam",ep,double.class);next.setAccessible(true);for(int i=0;i<100;i++){double x=120+(i%10)*29,y=10+(i/10)*25,dir=(i%7-3)*.4;Object p=point(ep,x,y,dir),q=next.invoke(ray,p,4.0);w.printf(java.util.Locale.ROOT,"R,%d,%d,%.17g,%.17g,%.17g%n",kind,i,number(q,"x"),number(q,"y"),number(q,"dir"));}}}
  if(args[0].equals("rgb")){Class<?> c=load(l,"RGBcolor");Constructor<?> con=c.getConstructor();Method m=c.getMethod("setFromxy",double.class,double.class);Field ntsc=c.getField("isNTSC"),color=c.getField("color");for(int k=0;k<2;k++)for(int i=0;i<2000;i++){Object o=con.newInstance();ntsc.setBoolean(o,k==1);m.invoke(o,(i%40+.5)/50.0,(i/40+.5)/60.0);java.awt.Color rgb=(java.awt.Color)color.get(o);w.printf("%d,%d,%d,%d,%d%n",k,i,rgb.getRed(),rgb.getGreen(),rgb.getBlue());}}
  if(args[0].equals("spec")){Class<?> c=load(l,"SpecColor");Method m=c.getDeclaredMethod("setColor",float[].class);m.setAccessible(true);for(int i=0;i<2000;i++){float[] data=new float[16];for(int j=0;j<16;j++)data[j]=(float)((i*17+j*23)%103/102.0);java.awt.Color rgb=(java.awt.Color)m.invoke(null,(Object)data);w.printf("%d,%d,%d,%d%n",i,rgb.getRed(),rgb.getGreen(),rgb.getBlue());}}
  w.close();
 }
}
