import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import{diffractionAmplitude,beamValue,besselJ1,slitFactor,fft,transform1D,transform2D,propagationInitial,propagate,aperturePass,cieValue,reflectionWaves,transverseBeam}from'../assets/legacy-optics-physics.mjs';
const specs=JSON.parse(fs.readFileSync(new URL('../src/legacy-optics.json',import.meta.url)));
const close=(a,b,e=1e-9)=>assert.ok(Math.abs(a-b)<=e*(1+Math.abs(b)),`${a} != ${b}`);
test('legacy optics manifest maps thirty-nine actual Java programs, not SWF duplicates',()=>{assert.equal(specs.length,39);assert.equal(new Set(specs.map(s=>s.id)).size,39);for(const s of specs){assert.equal(s.provenance.format,'Java applet');assert.match(s.provenance.archiveSHA256,/^[a-f0-9]{64}$/);assert.ok(s.lessonId.startsWith('5-'));for(const p of s.parameters)assert.ok(p.min<=p.value&&p.value<=p.max);}});
test('diffraction finite center, symmetry and first zeros',()=>{for(const [kind,p,x]of[['single',{wavelength:500,width:1},Math.PI/4],['many',{wavelength:500,spacing:2,ratio:.5,count:2},Math.PI/4],['rectangle',{wavelength:500,width:1,height:1.5},Math.PI]]){close(diffractionAmplitude(kind,p,0),1);close(diffractionAmplitude(kind,p,x),0);for(let k=0;k<80;k++)close(diffractionAmplitude(kind,p,k*.23)**2,diffractionAmplitude(kind,p,-k*.23)**2);}close(diffractionAmplitude('circular',{wavelength:500,radius:1},0),1);close(diffractionAmplitude('circular',{wavelength:500,radius:1},3.831705970),0,1e-8);});
test('Bessel and slit values match separately executed original Java math',()=>{close(besselJ1(1),.44005058574493355);close(besselJ1(5),-.3275791375914646);close(slitFactor(.5,30),.045212988447963606);for(let n=1;n<=30;n++)close(slitFactor(Math.PI,n),n%2?1:-1);});
test('complex Gaussian field and intensity satisfy original Rayleigh law',()=>{const p={w0:1,z0:2};close(beamValue('gaussian',p,0,0,2).intensity,.5);close(beamValue('gaussian',p,1,0,0).intensity,Math.exp(-2));for(let i=0;i<100;i++){const b=beamValue('gaussian',p,(i-50)/23,.3,i/40);close(b.real**2+b.imag**2,b.intensity);}const e=beamValue('elliptic',{wx0:.8,wy0:1.2,lambda:1.4,delta:.4},-.95,-.65,-.96);close(e.intensity,.07879693766043319);});
test('Hermite modes preserve parity and nodes',()=>{const p={w0:1,z0:2.4,m:2,n:3};close(beamValue('hermite',p,.8,0,0).amplitude,0);const a=beamValue('hermite',p,.8,.4,.8),b=beamValue('hermite',p,-.8,-.4,.8);close(a.intensity,b.intensity);close(a.amplitude,-b.amplitude);});
test('FFT forward-inverse round trip and Parseval',()=>{const a=Float64Array.from({length:256},(_,i)=>Math.sin(i*.31)+.7*Math.cos(i*.13)),f=fft(a),v=fft(f.re,f.im,true);for(let i=0;i<a.length;i++){close(a[i],v.re[i]);close(v.im[i],0);}close(a.reduce((s,v)=>s+v*v,0),f.re.reduce((s,v,i)=>s+(v*v+f.im[i]**2)/a.length,0));});
test('FFT original location/offset controls affect complex phase and zero frequency',()=>{const base=transform1D({shape:1,xScale:5,position:0,offset:0}),shift=transform1D({shape:1,xScale:5,position:10,offset:0}),offset=transform1D({shape:1,xScale:5,position:0,offset:2});close(base.power[256],shift.power[256],1e-8);close(offset.re[256]-base.re[256],102.4);assert.ok(Math.abs(shift.im[260])>1e-4);for(let shape=0;shape<=11;shape++)assert.ok(transform1D({shape,xScale:5,position:0,offset:0,seed:1}).power.every(Number.isFinite));});
test('2D diffraction is the Fourier transform of each actual aperture',()=>{for(let shape=0;shape<=12;shape++){const f=transform2D({shape,xScale:5,yScale:5,rotation:30,seed:1},128);assert.ok(f.power.every(Number.isFinite));const sum=f.aperture.reduce((a,b)=>a+b,0);close(f.power[128*64+64],sum*sum);}});
test('propagation evolves all four implemented modes, conserves power and supports aperture turns',()=>{for(let shape=0;shape<=3;shape++){const s=propagationInitial(shape,50),a=propagate(s,0),b=propagate(s,800),sum=w=>w.power.reduce((a,b)=>a+b,0);close(sum(a),sum(b),1e-9);assert.ok(Math.abs(a.power[522]-b.power[522])>1e-4);const filtered=propagate(aperturePass(b,100),0);for(let i=0;i<1024;i++)if(i<=462||i>=562)close(filtered.power[i],0,1e-8);assert.ok(filtered.power.every(Number.isFinite));}});
test('CIE source table interpolation, boundary and NTSC conversion preserve negative values',()=>{close(cieValue(555)[1],1);const a=cieValue(550),b=cieValue(555),half=cieValue(552.5);for(let k=0;k<3;k++)close(half[k],(a[k]+b[k])/2);assert.deepEqual(cieValue(830),[0,0,0]);assert.ok(cieValue(500,true)[0]<0);});
test('reflection phase produces a node at a phase-reversing boundary',()=>{for(let t=0;t<100;t++)close(reflectionWaves(525,t,180).resultant,0);close(reflectionWaves(525,20,0).resultant,2*reflectionWaves(525,20,0).incident);assert.ok(Math.abs(reflectionWaves(100,0,0).resultant-reflectionWaves(100,20,0).resultant)>.1);});

test('standalone Hermite transverse modes preserve original radius, nodes and complex power',()=>{const p={m:0,n:0,z:0};close(transverseBeam(p,0,0).w,50/Math.PI);close(transverseBeam(p,0,0).intensity,1);close(transverseBeam(p,50/Math.PI,0).amplitude,Math.exp(-(1.414**2)/2));for(let m=0;m<=5;m++)for(let n=0;n<=5;n++){const p={m,n,z:50},b=transverseBeam(p,3,7);close(b.real**2+b.imag**2,b.intensity);assert.ok(Number.isFinite(b.phase));}close(transverseBeam({m:1,n:0,z:0},0,10).intensity,0);});

import {lensImage,thinLensRay,traceOptics,instrumentConfig,sourceIndex,nextSourceRay,snell,filmIntensity,filmTheory,filmGap,ringGap,sourceSpecColor,sourceWhiteFringe,polarPacket,polarization,phasor,chromaticity} from '../assets/legacy-optics-rest-physics.mjs';
test('thin-lens image equation handles real, virtual and focal singular states',()=>{for(const f of[-200,-50,50,200])for(const d of[5,25,50,100,200,500]){const q=lensImage(d,20,f);if(d===f){assert.equal(q.finite,false);assert.equal(q.distance,null);}else{close(1/d+1/q.distance,1/f);close(q.height,-20*q.distance/d);}}});
test('original ThinLens aperture modes distinguish blocked, stray and unlimited rays',()=>{const c={kind:0,x:0,y:0,dir:0,length:50,f:80},p={x:-100,y:40,dir:0};assert.equal(thinLensRay({...c,mode:0},p).blocked,true);assert.equal(thinLensRay({...c,mode:1},p).stray,true);const q=thinLensRay({...c,mode:2},p);assert.equal(q.blocked,false);assert.equal(q.stray,false);close(q.dir,Math.atan(-.5));const mirror=thinLensRay({...c,kind:2,mode:2},{x:100,y:0,dir:Math.PI});close(mirror.dir,0);});
test('all eight source instrument families and discrete themes yield finite ray geometry',()=>{for(const kind of['single','singlestop','twolens','threelens','microscope','kepler','newton','binoculars'])for(let theme=0;theme<=5;theme++){const c=instrumentConfig(kind,{theme});const o={x:c.object.x+c.object.length*Math.cos(c.object.dir),y:c.object.y+c.object.length*Math.sin(c.object.dir)};for(const ray of traceOptics(c.components,o,13,true))for(const q of ray)assert.ok(Number.isFinite(q.x)&&Number.isFinite(q.y)&&Number.isFinite(q.dir));}});
test('source refraction conserves Snell law and total internal reflection is explicit',()=>{for(const n1 of[1,1.3,1.5,2])for(const n2 of[1,1.3,1.5,2])for(let angle=0;angle<=89;angle++){const q=snell(n1,n2,angle);if(!q.totalReflection)close(n1*Math.sin(angle*Math.PI/180),n2*Math.sin(q.angle*Math.PI/180));else assert.ok(n1>n2);}const p={x:200,y:50,dir:0};const q=nextSourceRay(p,4,{kind:1,r:1.5});close(q.x,204);close(q.y,50);});
test('original material masks and graded fiber endpoints preserve boundary conventions',()=>{close(sourceIndex(100,50,{kind:24,par3:2}),2);close(sourceIndex(100,75,{kind:24,par3:2}),1);close(sourceIndex(100,62.5,{kind:22,par3:2}),1.5);close(sourceIndex(100,62.5,{kind:23,par3:2}),1.75);close(sourceIndex(350,130,{kind:15,r:1.45}),1.45);});
test('Newton rings retain dark contact and finite coherence fades to half intensity',()=>{close(ringGap(0,10),0);close(filmIntensity(0,550),0,1e-12);close(filmIntensity(20000,550,true),.5);assert.ok(ringGap(10,10)>ringGap(5,10));for(const shape of[0,1,2,3])for(const c of[0,1,200,600])for(let x=0;x<=300;x+=10)assert.ok(Number.isFinite(filmGap(shape,c,x)));});
test('original float spectral matcher is exact for black and white input and finite under all wavelengths',()=>{assert.deepEqual(sourceSpecColor(new Array(16).fill(0)).rgb,[0,0,0]);const q=sourceSpecColor(new Array(16).fill(1));assert.deepEqual(q.rgb,[255,242,231]);for(let gap=0;gap<=15000;gap+=50){const w=sourceWhiteFringe(gap,true);assert.ok(w.rgb.every(v=>Number.isInteger(v)&&v>=0&&v<=255));assert.ok(w.intensity>=0&&w.intensity<=1.1);}});
test('finite polarization packets preserve original 50/70-wave distributions and crossed apertures',()=>{let seenUpper=false,seenLower=false;for(let i=0;i<70;i++){const q=polarPacket('analyzer',i,300,{analyzer:true});assert.ok(q.train>=100&&q.train<300);assert.ok(q.wavelength>=38&&q.wavelength<73);assert.ok(q.xpos>=60&&q.xpos<310);const v=q.at(150);if(v.z>350&&q.xpos>200&&q.xpos<310){close(v.ex,0);close(v.ey,0);seenUpper=true;}if(v.z>350&&q.xpos>60&&q.xpos<170){close(v.ex,0);seenLower=true;}}assert.ok(seenUpper&&seenLower);const a=polarPacket('ensemble',2,0),b=polarPacket('ensemble',2,10);close(b.zpos-a.zpos,30);});
test('phasor cancellation and circular polarization keep physical amplitude',()=>{const q=phasor({a1:50,a2:50,phase1:0,phase2:180,omega1:1,omega2:1},3);close(q.amplitude,0);for(let t=0;t<100;t++){const q=polarization('circular',{wavelength:80},t,35);close(q.ex*q.ex+q.ey*q.ey,2500);}for(const medium of[0,1,2,3])for(const thickness of[1,50,150]){const q=filmTheory({medium,thickness,wavelength:550},30);assert.ok(q.intensity>=0&&q.intensity<=1);}});
