import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {instrumentAS3Observer} from './modern-next-as3-observer.mjs';import {inspectSWF} from './swf-runtime-probe.mjs';
const original=fs.readFileSync(new URL('../assets/flash/original/phtml/modern/molecular/moenergy/rot3dmo.swf',import.meta.url)),abc=Buffer.from([1]),tag=(code,data)=>{const h=Buffer.alloc(6);h.writeUInt16LE(code<<6|63);h.writeUInt32LE(data.length,2);return Buffer.concat([h,data]);};
function preserved(input,output){const a=inspectSWF(input),b=inspectSWF(output),at=b.tags.findIndex(t=>t.code===1)-4,remaining=b.tags.filter((t,i)=>i<at||i>=at+4);assert.equal(remaining.length,a.tags.length);remaining.forEach((t,i)=>assert.ok(b.body.subarray(t.start,t.end).equals(a.body.subarray(a.tags[i].start,a.tags[i].end))));assert.ok(a.body.subarray(8,a.offset).equals(b.body.subarray(8,b.offset)));assert.equal(a.body[3],b.body[3]);assert.equal(b.body.readUInt32LE(4),b.body.length);}
function sprite(id,children=[]){const h=Buffer.alloc(4);h.writeUInt16LE(id);h.writeUInt16LE(1,2);return tag(39,Buffer.concat([h,...children,tag(1,Buffer.alloc(0)),tag(0,Buffer.alloc(0))]));}
function synthetic(extra){const s=inspectSWF(original),out=[s.body.subarray(0,s.offset)];for(const t of s.tags){if(t.code===1)out.push(...extra);out.push(s.body.subarray(t.start,t.end));}const b=Buffer.concat(out);b.writeUInt32LE(b.length,4);return b;}
test('observer preserves every original tag including root SymbolClass and all ABC plus stage/fps/version',()=>{const r=instrumentAS3Observer(original,abc);preserved(original,r.bytes);const s=inspectSWF(r.bytes),symbols=s.tags.filter(t=>t.code===76);assert.ok(symbols.length>=2);assert.equal(symbols.at(-1).data.readUInt16LE(2),r.characterId);assert.notEqual(r.characterId,0);});
test('character allocation avoids recursively nested definitions and root placement depths',()=>{const p=Buffer.alloc(6);p[0]=6;p.writeUInt16LE(65530,1);p.writeUInt16LE(65530,3);const input=synthetic([sprite(65530,[sprite(65529)]),tag(26,p)]),r=instrumentAS3Observer(input,abc);assert.equal(r.characterId,65528);assert.equal(r.depth,65529);preserved(input,r.bytes);});
test('a conflicting original symbol class name is rejected instead of replaced',()=>{const d=Buffer.alloc(4);d.writeUInt16LE(1);d.writeUInt16LE(65530,2);const input=synthetic([tag(76,Buffer.concat([d,Buffer.from('PhysicaAS3ObserverModern\0')]))]);assert.throws(()=>instrumentAS3Observer(input,abc),/collides/);});
test('a same-named observer class in original ABC is rejected conservatively',()=>{const input=synthetic([tag(82,Buffer.concat([Buffer.alloc(4),Buffer.from('original\0PhysicaAS3ObserverModern')]))]);assert.throws(()=>instrumentAS3Observer(input,abc),/collides/);});
test('observer source uses no original method calls or assignments',()=>{const s=fs.readFileSync(new URL('java/PhysicaAS3ObserverModern.as',import.meta.url),'utf8');assert.ok(!/\br(?:\.[\w]+|\[[^\]]+\])(?:\.[\w]+)*(?:\s*=(?!=)|\s*\()/.test(s.replace(/"[^"]*"/g,'')));assert.ok(s.includes('Event.ENTER_FRAME'));assert.ok(!/ExternalInterface|Timer|eval\(/.test(s));});
