import test from'node:test';import assert from'node:assert/strict';import{atomicPosition,atomicState,atomicGroup}from'../assets/modern-final69-atomic-physics.mjs';import{quantumState,boundBallState,quantumCSV}from'../assets/modern-final69-quantum-physics.mjs';import*as R from'../assets/modern-final69-relativity-physics.mjs';import{createFranck,cavityState,spectrumState,comptonState}from'../assets/modern-final69-photon-physics.mjs';import{maxSteps,controlsByType}from'../assets/modern-final69-specs.mjs';import{modernFinal69CSV}from'../assets/native-modern-final69.mjs';
test('periodic table separates complete lanthanide/actinide chains and individual data',()=>{const a=atomicState('table');assert.equal(a.entries.length,118);assert.equal(new Set(a.entries.map(p=>p.x+','+p.y)).size,118);assert.equal(atomicPosition(57).y,7);assert.equal(atomicPosition(89).y,8);assert.ok(atomicGroup(3,11));assert.ok(!atomicGroup(1,11));assert.equal(atomicState('semi').entries.length,72);assert.equal(atomicState('crystal',{element:14}).selected.symbol,'Si');});
test('covalent solver resolves distance-dependent tunnelling split without nonfinite values',()=>{const s={id:'flash-73be9774daba6348'},a=quantumState(s,{distance:.2,depth:100}),b=quantumState(s,{distance:.5,depth:100});assert.equal(a.energies.length,2);assert.ok(a.energies[1]>a.energies[0]);assert.ok(a.energies[1]-a.energies[0]>b.energies[1]-b.energies[0]);assert.ok(a.waves.flat().every(Number.isFinite));assert.equal(quantumCSV(a).split('\n').length,652);});
test('impurity eigenstates honor control variants and numerical CSV columns',()=>{const s={id:'flash-acf2dab16134634a'},a=quantumState(s,{factor:.8}),b=quantumState(s,{factor:1.2});assert.equal(a.energies.length,11);assert.notDeepEqual(a.energies,b.energies);const widths=new Set(quantumCSV(a).split('\n').map(r=>r.split(',').length));assert.equal(widths.size,1);});
test('two bound particles move from both wells with no nonfinite coordinates',()=>{const s={id:'flash-9b41f82783cf8a46'},a=quantumState(s,{mode:2}),b=quantumState(s,{mode:4});const q=boundBallState({},a,b,15);assert.ok(Object.values(q).every(Number.isFinite));assert.notEqual(q.x1,258);assert.notEqual(q.x2,280);});
test('Michelson photons meet only at the same optical-path step',()=>{const a=R.michelsonState(164);assert.deepEqual(a.d1,a.e1);assert.notDeepEqual(R.michelsonState(40).d1,R.michelsonState(40).e1);});
test('river comoving coordinates preserve relative boat motion',()=>{for(const n of[1,20,60]){const a=R.riverState({river:5},n),b=R.riverState({river:5,moving:true},n);assert.ok(Math.abs(a.x2-(b.x2-b.bank))<1e-9);assert.equal(a.y1,b.y1);}assert.ok(R.riverState({river:5},1500).finished);});
test('curved potential is finite at origin and integration really moves',()=>{assert.ok(Number.isFinite(R.curvedPotential(0,0)));assert.ok(R.curvedState({},10).y<180);assert.ok(R.curvedState({},10).trajectory.every(a=>a.every(Number.isFinite)));});
test('twin charts and both clocks share one source phase across turnaround',()=>{const a=R.twinState('twin',{beta:.8},251),b=R.twinState('twin',{beta:.8},252);assert.ok(b.x<a.x);assert.equal(a.earthClock/a.shipClock,a.gamma);assert.equal(a.time,251);assert.equal(a.earthClock,25);});
test('moving-observer pulse arrivals break simultaneity and source clocks synchronize locally',()=>{const a=R.simultaneousState({beta:.25},110);assert.ok(a.firstArrival<a.stationaryArrival);assert.ok(a.lastArrival>a.stationaryArrival);const b=R.clocksState({sync:true},100);assert.ok(b.clocks.find(a=>a.i===0&&a.j===0).synced);assert.ok(!b.clocks.find(a=>a.i===4&&a.j===3).synced);});
test('cavity and original Compton poses are deterministic finite source states',()=>{const a=cavityState({seed:2},100);assert.deepEqual(a,cavityState({seed:2},100));assert.ok(a.lines.flat().every(Number.isFinite));assert.notDeepEqual(comptonState(0).photon,comptonState(35).photon);});
test('Franck-Hertz inelastic collision loses the selected excitation quantum',()=>{const a=createFranck({voltage:7,filament:0,gas:0});a.q.px[0]=100;a.q.vx[0]=100;const incoming=(100+7/50)**2/500;a.step();assert.ok(Math.abs((a.q.vx[0]**2+a.q.vy[0]**2)/500-(incoming-4.9))<1e-9);});
test('original Rodrigues projection preserves lengths and known missing spectral bins',()=>{const q=spectrumState({});for(const row of q.matrix)assert.ok(Math.abs(row.reduce((a,b)=>a+b*b,0)-1)<1e-12);assert.deepEqual(q.rays.filter(a=>!a.present).map(a=>a.wavelength),[550,620]);assert.notDeepEqual(q.project([130,100,0]),spectrumState({yaw:90,pitch:30}).project([130,100,0]));});
test('static sources have no false playback range; original source controls have valid defaults',()=>{for(const t of['table','crystal','semi','bond','impurity','spectrum'])assert.equal(maxSteps[t],0);for(const cs of Object.values(controlsByType))for(const c of cs)if(c.min!==undefined)assert.ok(c.value>=c.min&&c.value<=c.max);});
test('structured CSV safely quotes comma-containing numerical series',()=>{const csv=modernFinal69CSV({time:1,path:[[1,2],[3,4]]},{type:'worldline'});assert.ok(csv.includes('"[[1,2],[3,4]]"'));assert.ok(csv.split('\n').every(a=>/^".*",".*"$/.test(a)||a==='quantity,value'));});

test('Franck-Hertz manual controls preserve current particles, stop tracking; tracking restarts at zero voltage',()=>{const a=createFranck({voltage:7,filament:7,gas:0});a.seek(120);const px=[...a.q.px];a.setInput('voltage',12);assert.deepEqual(a.q.px,px);assert.equal(a.q.volt,12);assert.equal(a.q.dataCounter,0);a.setInput('auto',true);assert.equal(a.q.volt,0);assert.equal(a.q.isAuto,true);a.setInput('filament',8);assert.equal(a.q.isAuto,false);assert.equal(a.q.filV,8);});

test('independent source sprite decoder preserves signed fixed-point scale, rotation, twips and frame transport',async()=>{
  const {decodeComptonSprite}=await import('./modern-final69-compton-reference.mjs');
  const bits='1'+'10010'+(98304).toString(2).padStart(18,'0')+(2**18-32768).toString(2).padStart(18,'0')+'1'+'10001'+(16384).toString(2).padStart(17,'0')+(2**17-16384).toString(2).padStart(17,'0')+'01110'+(5000).toString(2).padStart(14,'0')+(2**14-2000).toString(2).padStart(14,'0');
  const padded=bits.padEnd(Math.ceil(bits.length/8)*8,'0'),matrix=Buffer.from(padded.match(/.{8}/g).map(v=>parseInt(v,2)));
  const header=Buffer.alloc(4);header.writeUInt16LE(34,0);header.writeUInt16LE(1,2);
  const place=depth=>{const data=Buffer.alloc(4);data.writeUInt16LE(1,0);data.writeUInt16LE(depth,2);const body=Buffer.concat([data,matrix]),tag=Buffer.alloc(2);tag.writeUInt16LE((4<<6)+body.length);return Buffer.concat([tag,body]);};
  const frames=decodeComptonSprite(Buffer.concat([header,place(26),place(29),Buffer.from([64,0,0,0])]));
  assert.equal(frames.length,1);for(const k of['photon','electron'])assert.deepEqual(frames[0][k],{a:1.5,d:-.5,e:.25,c:-.25,x:250,y:-100});
});
