import test from 'node:test';import assert from 'node:assert/strict';import {fundamentalSpecs,defaults,trajectory,initial,step,energy}from '../assets/fundamental-physics.mjs';
const find=t=>Object.values(fundamentalSpecs).find(s=>s.type===t);
test('All 15 source-specific models remain finite at each control endpoint through the entire timeline',()=>{assert.equal(Object.keys(fundamentalSpecs).length,15);for(const s of Object.values(fundamentalSpecs)){const p=defaults(s);for(const q of [p,...s.controls.flatMap(c=>[c.min,c.max].map(v=>({...p,[c.key]:v})))])for(const a of trajectory(s,q))for(const [k,v]of Object.entries(a))if(typeof v==='number')assert.ok(Number.isFinite(v),s.type+' '+k);}});
test('Undamped harmonic analysis retains source mass, period and bounded energy drift',()=>{const s=find('osc_harm1'),p=defaults(s),v=trajectory(s,p),e0=energy(s,p,v[0])[2];assert.equal(p.mass,6);const h=s.constants.dt/s.constants.substeps,omega=Math.sqrt(s.constants.k/p.mass),bound=h*omega/(2-h*omega);assert.ok(Math.max(...v.map(a=>Math.abs(energy(s,p,a)[2]/e0-1)))<=bound+1e-8);});
test('Damping removes energy, rather than only shrinking the drawn spring',()=>{const s=find('springmot_damped'),p=defaults(s),v=trajectory(s,p);assert.ok(energy(s,p,v[150])[2]<energy(s,p,v[0])[2]*.001);});
test('Scripted collisions preserve pre/post scene intervals and stationary endpoints',()=>{const s=find('col1d'),v=trajectory(s,{});assert.equal(v[9].x,25);assert.equal(v[30].x,125);assert.equal(v[50].y,230);assert.deepEqual([v[74].x,v[74].y],[145,230]);});
test('Ballistic source holds its last rising position at 100 and afterwards',()=>{const s=find('ballisticpen'),v=trajectory(s,{});assert.equal(v[30].x,170);assert.equal(v[30].woodX,200);for(const n of [100,101,149])assert.equal(v[n].woodX,v[99].woodX);});
test('Coulomb boundary reset stops the model; attraction and repulsion retain signs',()=>{const s=find('coulomblaw'),p=defaults(s),v=trajectory(s,p);assert.equal(v[1].stopped,true);assert.equal(v[1].x,450);for(const sign of [-1,1])assert.equal(Math.sign(step(s,{...p,position:200,sign},initial(s,{...p,position:200,sign})).F),sign);});
test('Wall collisions reverse only the contacted velocity component',()=>{const s=find('cnstmom2'),p=defaults(s),a={...initial(s,p),x:469,vx:2,vy:1},b=step(s,p,a);assert.equal(b.vx,-2);assert.equal(b.vy,1);assert.equal(b.x,461);});
