import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createOpticsFinal69Model}from'../assets/optics-final69-model.mjs';const specs=JSON.parse(fs.readFileSync('src/native-optics-final69.json'));async function model(type){return createOpticsFinal69Model(specs.find(s=>s.type===type));}
test('Airy resolution shrinks when aperture diameter doubles',async()=>{const m=await model('resolution'),c=specs.find(s=>s.type==='resolution').controls.find(c=>c.clip==='bSlider');m.set(c,40);const a=m.timeline.adDiameter;m.set(c,80);assert.equal(m.timeline.adDiameter,a/2);assert.ok(Math.abs(m.timeline.bessel1(3.83170597))<1e-8);});
test('Spherical ideal pupil exactly follows original sagitta and focal point',async()=>{const m=await model('pupil'),t=m.timeline;assert.equal(t.pupilFtn[0][0],0);assert.ok(Math.abs(t.pupilFtn[10][0]-(200-Math.sqrt(200**2-100**2)))<1e-12);assert.equal(t.focalP.sDir.Z,150);});
test('Zernike fourth-order default radial polynomial includes centre and edge',async()=>{const m=await model('aberration');assert.equal(m.timeline.pupilFtn[0][0],1);assert.equal(m.timeline.pupilFtn[10][0],1);});
test('Total reflection critical angle follows actual n and restarts after finite completion',async()=>{const m=await model('total');m.tick();assert.ok(Math.abs(Math.sin(m.timeline.angC)-1/m.timeline.n)<1e-12);let n=0;while(!m.finished&&n++<725)m.tick();assert.ok(m.finished);m.seek(0);assert.equal(m.step,0);assert.ok(!m.finished);assert.ok(m.tick());});
test('Crystal displacement advances same clock as electric-field and gray springs',async()=>{const m=await model('crystal'),t=m.timeline;m.tick();assert.equal(t.time,.1);assert.ok(Math.abs(t.ball0._y-(90+20*Math.sin(-.1*2.5)))<1e-10);assert.ok(t.graphic.graphics.items.length>0);});
test('LC Jones propagation is finite and normalized for default birefringent optical medium',async()=>{const m=await model('stn'),t=m.timeline;assert.ok(Math.abs(t.inJV.intensity()-1)<1e-12);assert.ok(Math.abs(t.outJV.intensity()-1)<1e-12);m.tick();assert.equal(t.currentTime,.1);assert.ok(t.calcE(t.currentJV,t.currentTime).every(Number.isFinite));});
test('Poincare actual elliptic electric vectors evolve and preserve finite state',async()=>{const m=await model('poincare'),t=m.timeline,a=t.calcE(t.currentJV1,0);m.tick();assert.equal(t.currentTime,.2);assert.notDeepEqual(t.calcE(t.currentJV1,t.currentTime),a);});
test('Static optical geometries remain static and contain separately authored SVG primitives',async()=>{for(const type of['fresnel','kerr','faraday','jones','scattering']){const m=await model(type);assert.ok(m.timeline.children.length>0);assert.equal(m.step,0);}});
